# Build settings
markdown:    kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge
gems:
  - jekyll-admin
  - jekyll-paginate

# Site settings
title: "Tomas Alabes' Blog"
description: My personal site's Blog

email: tomas.alabes@mail.mail
#blog logo
logo: "/assets/images/logos/twoLinesLogo.svg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Tomas Alabes'
author: 'Tomas Alabes'

author:
  name: "Tomas Alabes"
  bio: "Passionate Software Engineer from Argentina living in Silicon Valley."

author_image: "/assets/images/author.png"

paginate:	5

parentUrl: "http://tomasalabes.me/"
#parentUrl: "http://localhost:8000/"
url: "http://tomasalabes.me/blog/_site" # the base hostname & protocol for your site
#url: "http://localhost:8000/blog/_site" # the base hostname & protocol for your site
baseurl: "/blog/_site"
#used to display twitter cards
twitter_handle: '@tomasAlabes'

#fill in disqus shortname to use disqus
disqus: tomasalabesmeblog

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tomasAlabes
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=@tomasAlabes&nbsp;
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tomasAlabes
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:


  - icon: linkedin
    url:  https://www.linkedin.com/in/tomasalabes
    desc: Contact me via linkedin
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
